server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          basedir: 'git-temp'
#          uri: file:///D:/git-local/gtintel
          uri: https://github.com/bearswallow/spring-cloud-config-sample.git
          repos:
            app:
              basedir: 'git-temp'
              cloneOnStart: true
              force-pull: true
              pattern: '*'
#              uri: file:///D:/git-local/gtintel
              uri: https://github.com/bearswallow/spring-cloud-config-sample.git
              searchPaths:
                - '{profile}/'
                - '{profile}/{application}/'